# Generated by Django 6.0.2 on 2026-02-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
