# Generated by Django 6.0.2 on 2026-02-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_product_name_store_product_store_staff_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("store", "sku"), name="unique_store_sku"
            ),
        ),
    ]
