# Generated by Django 6.0.2 on 2026-02-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_product_sku_product_unique_store_sku"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="store",
        ),
        migrations.RemoveConstraint(
            model_name="product",
            name="unique_store_sku",
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.RemoveField(
            model_name="product",
            name="store",
        ),
        migrations.DeleteModel(
            name="Store",
        ),
    ]
